language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest --cov preprocessing
  - pylint preprocessing/test_preprocess.py
  - pylint preprocessing/preprocess.py
